// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datasource.proto

package com.grpc.proto.datasource;

public final class DatasourceProto {
  private DatasourceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DatasourceMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DatasourceMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020datasource.proto\"Y\n\rDatasourceMsg\022\013\n\003u" +
      "rl\030\001 \001(\t\022\027\n\017driverClassName\030\002 \001(\t\022\020\n\010use" +
      "rname\030\003 \001(\t\022\020\n\010password\030\004 \001(\t2F\n\021Datasou" +
      "rceService\0221\n\rGetDatasource\022\016.Datasource" +
      "Msg\032\016.DatasourceMsg\"\000B.\n\031com.grpc.proto." +
      "datasourceB\017DatasourceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DatasourceMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DatasourceMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DatasourceMsg_descriptor,
        new String[] { "Url", "DriverClassName", "Username", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
