// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datasource.proto

package com.grpc.proto.datasource;

public interface DatasourceMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DatasourceMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string url = 1;</code>
   */
  String getUrl();
  /**
   * <code>optional string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>optional string driverClassName = 2;</code>
   */
  String getDriverClassName();
  /**
   * <code>optional string driverClassName = 2;</code>
   */
  com.google.protobuf.ByteString
      getDriverClassNameBytes();

  /**
   * <code>optional string username = 3;</code>
   */
  String getUsername();
  /**
   * <code>optional string username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string password = 4;</code>
   */
  String getPassword();
  /**
   * <code>optional string password = 4;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
