// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu.proto

package com.grpc.proto.menu;

public final class MenuProto {
  private MenuProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MenuMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MenuMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nmenu.proto\"F\n\007MenuMsg\022\n\n\002id\030\001 \001(\t\022\013\n\003u" +
      "rl\030\002 \001(\t\022\022\n\npermission\030\003 \001(\t\022\016\n\006module\030\004" +
      " \001(\t23\n\013MenuService\022$\n\nGetAllMenu\022\010.Menu" +
      "Msg\032\010.MenuMsg\"\0000\001B\"\n\023com.grpc.proto.menu" +
      "B\tMenuProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MenuMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MenuMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MenuMsg_descriptor,
        new String[] { "Id", "Url", "Permission", "Module", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
