// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu.proto

package com.grpc.proto.menu;

public interface MenuMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MenuMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string url = 2;</code>
   */
  String getUrl();
  /**
   * <code>optional string url = 2;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>optional string permission = 3;</code>
   */
  String getPermission();
  /**
   * <code>optional string permission = 3;</code>
   */
  com.google.protobuf.ByteString
      getPermissionBytes();

  /**
   * <code>optional string module = 4;</code>
   */
  String getModule();
  /**
   * <code>optional string module = 4;</code>
   */
  com.google.protobuf.ByteString
      getModuleBytes();
}
