// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.grpc.proto.user;

public interface RoleMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoleMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string code = 2;</code>
   */
  String getCode();
  /**
   * <code>optional string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>optional string name = 3;</code>
   */
  String getName();
  /**
   * <code>optional string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
