// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.grpc.proto.user;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRoleMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserRoleMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoleMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nuser.proto\"\\\n\013UserRoleMsg\022\n\n\002id\030\001 \001(\t\022" +
      "\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\035\n\013R" +
      "oleMsgList\030\004 \003(\0132\010.RoleMsg\"1\n\007RoleMsg\022\n\n" +
      "\002id\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\014\n\004name\030\003 \001(\t26\n" +
      "\013UserService\022\'\n\007GetUser\022\014.UserRoleMsg\032\014." +
      "UserRoleMsg\"\000B\"\n\023com.grpc.proto.userB\tUs" +
      "erProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserRoleMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserRoleMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserRoleMsg_descriptor,
        new String[] { "Id", "Username", "Password", "RoleMsgList", });
    internal_static_RoleMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoleMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoleMsg_descriptor,
        new String[] { "Id", "Code", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
