// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.grpc.proto.user;

public interface UserRoleMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRoleMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string username = 2;</code>
   */
  String getUsername();
  /**
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string password = 3;</code>
   */
  String getPassword();
  /**
   * <code>optional string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>repeated .RoleMsg RoleMsgList = 4;</code>
   */
  java.util.List<RoleMsg>
      getRoleMsgListList();
  /**
   * <code>repeated .RoleMsg RoleMsgList = 4;</code>
   */
  RoleMsg getRoleMsgList(int index);
  /**
   * <code>repeated .RoleMsg RoleMsgList = 4;</code>
   */
  int getRoleMsgListCount();
  /**
   * <code>repeated .RoleMsg RoleMsgList = 4;</code>
   */
  java.util.List<? extends RoleMsgOrBuilder>
      getRoleMsgListOrBuilderList();
  /**
   * <code>repeated .RoleMsg RoleMsgList = 4;</code>
   */
  RoleMsgOrBuilder getRoleMsgListOrBuilder(
          int index);
}
